### ISSUE TITLE
Unable to access nested templates stored in S3

### ISSUE THREAD

**Issue by OhansonB** [aws-ia/cfn-ps-connect-integration-aspect-wfm#19]
When recently attempting to deploy this newest version of the Alvaria WFM integration for Amazon Connect we immediately receive an Access Denied error in CloudFormation relating to the creation of the nested Agent Productivity and Real-Time Adherence stacks. We have initially attempted to deploy "aspect-wfm-ap-and-rta.template.yaml", which resulted in errors creating the logical resources named ApStack and RtaStack. 

CloudFormation parameters QSS3BucketName, QSS3BucketRegion, and QSS3KeyPrefix were left to default which resolved to values of "aws-ia", "eu-west-2", and "connect-integration-aspect-wfm/" respectively.

Our investigation into this suggests that the template objects stored in the S3 buckets specified under TemplateURL for the two affected resources are either not public, or do not exist. When you enter the URLs specified in th TemplateURL resource parameters (e.g.,: https://aws-ia-eu-west-2.s3.eu-west-2.amazonaws.com/connect-integration-aspect-wfm/templates/aspect-wfm-ap-kda.template.yaml) into your browser an Access Denied error is presented. 

We worked around this issue by downloading the equivalent template using the URL from the prior version of this integration, which is: https://aws-quickstart-eu-west-2.s3.eu-west-2.amazonaws.com/connect-integration-aspect-wfm/templates/aspect-wfm-ap-kda.template.yaml. This was downloaded CloudFormation template was then manually uploaded to tge CloudFormation console, and the previous version(s) of the other templates were deployed successfully.

**Comment by vsnyc** [comment]
The prefix at which the file has been updated to is cfn-ps-connect-integration-aspect-wfm. i.e.
https://aws-ia-eu-west-2.s3.eu-west-2.amazonaws.com/cfn-ps-connect-integration-aspect-wfm/templates/aspect-wfm-ap-kda.template.yaml

A workaround is to explicitly set QSS3KeyPrefix to `cfn-ps-connect-integration-aspect-wfm` when deploying the template.

The solution is to update the QSS3KeyPrefix Parameter default value to `cfn-ps-connect-integration-aspect-wfm`. Would you like to test this and create a PR with the fix?

**Comment by DBurkhead** [comment]
@OhansonB thanks for reporting this issue. It should be fixed in the current version of the QuickStarts.
